jobs:
  include:
    - os: linux
      env: BUILDARCH=x64
      dist: trusty
    - os: linux
      env: BUILDARCH=arm64
      dist: trusty
    - os: linux
      env: BUILDARCH=arm
      dist: trusty

language: node_js
node_js: "12.14.1"

install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"
  - . install_deps.sh
  - . get_repo.sh
  - . check_tags.sh

script:
  - ./build.sh

before_deploy:
  - ./sum.sh

deploy:
  provider: releases
  skip_cleanup: true
  overwrite: true
  name: $LATEST_MS_TAG
  token: $GITHUB_TOKEN
  file_glob: true
  file:
    - ./*.sha256
    - ./*.zip
    - ./*.tar.gz
    - ./*.deb
    - ./*.rpm
    - ./*.AppImage
    - ./*.AppImage.zsync
  on:
    all_branches: true
    condition: $SHOULD_BUILD = yes

after_deploy:
  - ./update_version.sh
