name: insider-linux

on:
  workflow_dispatch:
    inputs:
      release_version:
        type: string
        description: Forced release version
  schedule:
    - cron: '0 8 * * *'
  push:
    branches: [ insider ]
    paths-ignore:
    - '**/*.md'
  pull_request:
    branches: [ insider ]
    paths-ignore:
    - '**/*.md'

jobs:
  check:
    runs-on: ubuntu-latest
    container:
      image: vscodium/vscodium-linux-build-agent:bionic-x64
      env:
        VSCODE_QUALITY: insider
    outputs:
      MS_COMMIT: ${{ env.MS_COMMIT }}
      MS_TAG: ${{ env.MS_TAG }}
      RELEASE_VERSION: ${{ env.RELEASE_VERSION }}
      SHOULD_BUILD: ${{ env.SHOULD_BUILD }}
      SHOULD_DEPLOY: ${{ env.SHOULD_DEPLOY }}

    steps:
      - uses: actions/checkout@v3
        with:
          ref: insider

      - name: Clone VSCode repo
        env:
          RELEASE_VERSION: ${{ github.event.inputs.release_version }}
        run: ./get_repo.sh

      - name: Check PR or cron
        run: ./check_cron_or_pr.sh

      - name: Save repositories
        uses: actions/upload-artifact@v3
        with:
          name: repositories
          path: .
        if: needs.check.outputs.SHOULD_BUILD == 'yes' || needs.check.outputs.SHOULD_DEPLOY == 'yes'

  dependencies:
    needs: check
    runs-on: ubuntu-latest
    container:
      image: ${{ matrix.image }}
    strategy:
      fail-fast: false
      matrix:
        include:
        - vscode_arch: x64
          npm_arch: x64
          image: vscodium/vscodium-linux-build-agent:centos7-devtoolset8-x64
        - vscode_arch: arm64
          npm_arch: arm64
          image: vscodium/vscodium-linux-build-agent:centos7-devtoolset8-arm64
    if: needs.check.outputs.SHOULD_BUILD == 'yes' || needs.check.outputs.SHOULD_DEPLOY == 'yes'

    steps:
      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install Yarn
        run: npm install -g yarn

      - name: Restore repositories
        uses: actions/download-artifact@v3
        with:
          name: repositories

      - name: Install remote dependencies
        env:
          npm_config_arch: ${{ matrix.npm_arch }}
        run: ./install_remote_dependencies.sh

      - name: Save remote dependencies
        uses: actions/upload-artifact@v3
        with:
          name: remote-dependencies-${{ matrix.vscode_arch }}
          path: ./vscode/remote/node_modules

  build:
    needs: dependencies
    runs-on: ubuntu-latest
    container:
      image: ${{ matrix.image }}
      env:
        APP_NAME: VSCodium
        ASSETS_REPOSITORY: ${{ github.repository }}-insiders
        MS_COMMIT: ${{ needs.check.outputs.MS_COMMIT }}
        MS_TAG: ${{ needs.check.outputs.MS_TAG }}
        OS_NAME: linux
        RELEASE_VERSION: ${{ needs.check.outputs.RELEASE_VERSION }}
        SHOULD_BUILD: ${{ needs.check.outputs.SHOULD_BUILD }}
        SHOULD_DEPLOY: ${{ needs.check.outputs.SHOULD_DEPLOY }}
        VERSIONS_REPOSITORY: ${{ github.repository_owner }}/versions
        VSCODE_ARCH: ${{ matrix.vscode_arch }}
        VSCODE_QUALITY: insider
    strategy:
      fail-fast: false
      matrix:
        include:
        - vscode_arch: x64
          npm_arch: x64
          image: vscodium/vscodium-linux-build-agent:bionic-x64
        - vscode_arch: arm64
          npm_arch: arm64
          image: vscodium/vscodium-linux-build-agent:stretch-arm64
        - vscode_arch: armhf
          npm_arch: armv7l
          image: vscodium/vscodium-linux-build-agent:stretch-armhf
    if: needs.check.outputs.SHOULD_BUILD == 'yes' || needs.check.outputs.SHOULD_DEPLOY == 'yes'

    steps:
      - name: Install GH
        run: ./install_gh.sh

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install Yarn
        run: npm install -g yarn

      - name: Restore repositories
        run: ./restore_repositories.sh

      - name: Check existing VSCodium tags/releases
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./check_tags.sh
        if: env.SHOULD_DEPLOY == 'yes'

      - name: Compute cache key
        id: yarnCacheKey
        run: echo "::set-output name=value::$(node build/azure-pipelines/computeYarnCacheKey.js)"
        if: env.SHOULD_BUILD == 'yes'

      - name: Get yarn cache directory path
        id: yarnCacheDirPath
        run: echo "::set-output name=dir::$(yarn cache dir)"
        if: env.SHOULD_BUILD == 'yes'

      - name: Cache yarn directory
        uses: actions/cache@v3
        with:
          path: ${{ steps.yarnCacheDirPath.outputs.dir }}
          key: linux-${{ matrix.npm_arch }}-yarnCacheDir-${{ steps.yarnCacheKey.outputs.value }}
          restore-keys: linux-${{ matrix.npm_arch }}-yarnCacheDir-
        if: env.SHOULD_BUILD == 'yes'

      - name: Restore remote dependencies
       uses: actions/download-artifact@v3
        with:
          name: remote-dependencies-${{ matrix.vscode_arch }}
        if: ${{ matrix.vscode_arch }} != 'armhf'

      - name: Build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          npm_config_arch: ${{ matrix.npm_arch }}
        run: ./build.sh
        if: env.SHOULD_BUILD == 'yes'

      - name: Prepare assets
        run: ./prepare_assets.sh
        if: env.SHOULD_BUILD == 'yes' && env.SHOULD_DEPLOY == 'yes'

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.STRONGER_GITHUB_TOKEN }}
          GITHUB_USERNAME: ${{ github.repository_owner }}
        run: ./release.sh
        if: env.SHOULD_BUILD == 'yes' && env.SHOULD_DEPLOY == 'yes'

      - name: Update versions repo
        env:
          GITHUB_TOKEN: ${{ secrets.STRONGER_GITHUB_TOKEN }}
          GITHUB_USERNAME: ${{ github.repository_owner }}
        run: ./update_version.sh
        if: env.SHOULD_BUILD == 'yes' && env.SHOULD_DEPLOY == 'yes'

  aur:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
        - package_name: vscodium-insiders-bin
        - package_name: vscodium-insiders
    if: needs.check.outputs.SHOULD_DEPLOY == 'yes'

    steps:
      - name: Get version
        env:
          RELEASE_VERSION: ${{ needs.check.outputs.RELEASE_VERSION }}
        run: echo "PACKAGE_VERSION=${RELEASE_VERSION/-*/}" >> "${GITHUB_ENV}"

      - name: Publish ${{ matrix.package_name }}
        uses: zokugun/github-actions-aur-releaser@v1
        with:
          package_name: ${{ matrix.package_name }}
          package_version: ${{ env.PACKAGE_VERSION }}
          aur_private_key: ${{ secrets.AUR_PRIVATE_KEY }}
          aur_username: ${{ secrets.AUR_USERNAME }}
          aur_email: ${{ secrets.AUR_EMAIL }}

  snap:
    needs: build
    runs-on: ubuntu-latest
    env:
      APP_NAME: codium
      ASSETS_REPOSITORY: ${{ github.repository }}-insiders
      VSCODE_QUALITY: 'insider'
    strategy:
      fail-fast: false
      matrix:
        platform:
        - amd64
        - arm64
    # if: needs.check.outputs.SHOULD_DEPLOY == 'yes'
    if: ${{ false }}

    steps:
      - uses: actions/checkout@v3
        with:
          ref: insider

      - name: Check version
        env:
          ARCHITECTURE: ${{ matrix.platform }}
          SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.SNAP_STORE_LOGIN }}
        run: ./stores/snapcraft/check_version.sh

      - uses: docker/setup-qemu-action@v1
        if: env.SHOULD_DEPLOY == 'yes'

      - uses: diddlesnaps/snapcraft-multiarch-action@v1
        with:
          path: stores/snapcraft/insider
          architecture: ${{ matrix.platform }}
        id: build
        if: env.SHOULD_DEPLOY == 'yes'

      - uses: diddlesnaps/snapcraft-review-action@v1
        with:
          snap: ${{ steps.build.outputs.snap }}
          isClassic: 'true'
        if: env.SHOULD_DEPLOY == 'yes'

      - uses: snapcore/action-publish@master
        env:
          SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.SNAP_STORE_LOGIN }}
        with:
          snap: ${{ steps.build.outputs.snap }}
          release: edge
        if: env.SHOULD_DEPLOY == 'yes'
