name: CI

on:
  push:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: macOS-latest
    env:
      TRAVIS_OS_NAME: "osx"
    steps:
      - uses: actions/checkout@v2
        
      - name: Setup Node.js environment
        uses: actions/setup-node@v1.4.3
        with:
          node-version: 12.14.1
          
          
      - name: Clone VSCode repo
        run: |
          . get_repo.sh
          echo "::set-env name=LATEST_MS_TAG::$LATEST_MS_TAG"
          echo "::set-env name=LATEST_MS_COMMIT::$LATEST_MS_COMMIT"

      - name: Check existing VSCodium tags/releases
        run: |
          . check_tags.sh
          echo "::set-env name=SHOULD_BUILD::$SHOULD_BUILD"
          
      - name: Build
        run: ./build.sh

      - name: Zip release
        run: ./create_zip.sh
      
      - name: Release
        uses: softprops/action-gh-release@v1
        if: env.SHOULD_BUILD == "yes"
        with:
          tag_name: ${{ env.LATEST_MS_TAG }}
          files: |
            ./*.zip
            ./*.dmg
            ./*.sha256
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

